name: Auto Version and Release

on:
  pull_request:
    types: [closed]
    branches:
      - main # or 'master', depending on your default branch name

jobs:
  auto-release:
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write # Needed for creating releases
      pull-requests: write # Needed for creating PRs

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important for git history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      # - name: Write secret to config.yaml
      #   run: echo "${{ secrets.CONFIG_YAML }}" > config.yaml
      - name: Write secret to config.yaml
        run: |
          python -c "import os; file = open('.config.yaml', 'w'); file.write(os.environ['CONFIG_YAML']); file.close()"
        shell: bash
        env:
          YOUR_SECRET : ${{secrets.CONFIG_YAML}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          SUPER_STRATEGY_ID: test
        run: |
          pytest

      - name: Determine version bump type
        id: bump-type
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ $PR_TITLE =~ ^breaking:|^major: ]]; then
            echo "type=major" >> $GITHUB_OUTPUT
          elif [[ $PR_TITLE =~ ^feat:|^feature:|^minor: ]]; then
            echo "type=minor" >> $GITHUB_OUTPUT
          else
            echo "type=patch" >> $GITHUB_OUTPUT
          fi

      - name: Bump version
        id: bump-version
        run: |
          python bump_version.py ${{ steps.bump-type.outputs.type }}

      - name: Create Pull Request for version bump
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          title: 'Bump version to ${{ steps.bump-version.outputs.new_version }}'
          body: 'Automated version bump after merging PR #${{ github.event.pull_request.number }}'
          commit-message: 'Bump version to ${{ steps.bump-version.outputs.new_version }}'
      - name: Check outputs
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pull-request-url }}"

      - name: Auto-merge version bump PR
        run: gh pr merge --auto --merge "${{ steps.create-pr.outputs.pull-request-number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.bump-version.outputs.new_version }}
          name: Release v${{ steps.bump-version.outputs.new_version }}
          body: |
            Release of version ${{ steps.bump-version.outputs.new_version }}

            Changes included in this release:
            ${{ github.event.pull_request.title }}

            For more details, see PR #${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
